---
# Updating host files 
- name: Hostname | Updating Hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Hostname | Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].ansible_ssh_host }} {{ item }}"
    state: present
  with_items: "{{ groups.all }}"


# Sysctl Optimisations
- name: Systctl | Setting Dirty Ratio
  sysctl: 
    name: vm.dirty_ratio
    value: 15
    sysctl_set: yes
    state: present

- name: Systctl | Setting Dirty Background Ratio
  sysctl: 
    name: vm.dirty_ratio
    value: 5
    sysctl_set: yes
    state: present

- name: Systctl | Setting Swappiness
  sysctl: 
    name: vm.swappiness
    value: 1
    sysctl_set: yes
    state: present

- name: Systctl | net | Setting somaxconn
  sysctl: 
    name: net.core.somaxconn
    value: 4096
    sysctl_set: yes
    state: present

- name: Systctl | net | Setting tcp_fin_timeout
  sysctl: 
    name: net.ipv4.tcp_fin_timeout
    value: 30
    sysctl_set: yes
    state: present

- name: Systctl | net | Setting tcp_keepalive_time
  sysctl: 
    name: net.ipv4.tcp_keepalive_time
    value: 120
    sysctl_set: yes
    state: present

- name: Systctl | net | Setting tcp_max_syn_backlog
  sysctl: 
    name: net.ipv4.tcp_max_syn_backlog
    value: 4096
    sysctl_set: yes
    state: present

# Transparent Huge Pages Optimization
- name: THP | Copying THP config
  template: 
    src: "disable-transparent-hugepages.j2"
    dest: "/etc/init.d/disable-transparent-hugepages"
    owner: root
    group: root

- name: THP | Disabling THP
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - disable-transparent-hugepages

- name: THP | Creates tuned profile directory
  file:
    path: "/etc/tuned/no-thp"
    state: directory
    owner: root
    group: root

- name: THP | Copying tuned config
  template: 
    src: "tuned.conf.j2"
    dest: "/etc/tuned/no-thp/tuned.conf"
    owner: root
    group: root

# idempotent implementation using folder named "activated" as flag to activate tuned
- name: THP | no-thp tuned conf activated?
  stat:
    path: /etc/tuned/no-thp/activated
  register: nothp_activated

- name: THP | activating tuned conf
  command: tuned-adm profile no-thp
  when: nothp_activated.stat.exists == False

- name: THP | Creates tuned profile directory
  when: nothp_activated.stat.exists == False
  file:
    path: /etc/tuned/no-thp/activated
    state: directory
    owner: root
    group: root

- name: Yum | Install Yum packages
  yum:
    name:
      - ntp # Network Time Protocol Optimization
      - numactl
      - firewalld

- name: Systemd | Enable packages
  systemd:
    name: "{{ item }}"
    state: started
    enabled: True
  with_items:
    - ntpd
    - firewalld

- name: set timezone to Asia/Singapore
  timezone:
    name: Asia/Singapore