- name: Download Cloudera Repo
  get_url:
    url: https://archive.cloudera.com/cm6/6.1.0/redhat7/yum/cloudera-manager.repo
    dest: /etc/yum.repos.d/

- rpm_key:
    state: present
    key: https://archive.cloudera.com/cm6/6.1.0/redhat7/yum/RPM-GPG-KEY-cloudera

- name: Yum | Install Yum packages
  yum:
    name:
      - oracle-j2sdk1.8
      - cloudera-manager-daemons 
      - cloudera-manager-agent 
      - cloudera-manager-server


# idempotent implementation using folder named "activated" as flag to auto tls
- name: autotls | autotls?
  stat:
    path: /etc/ansibleFlags/autotls
  register: autotls

- name: autotls | autotls init
  command: sudo JAVA_HOME=/usr/java/jdk1.8.0_141-cloudera /opt/cloudera/cm-agent/bin/certmanager setup --configure-services
  when: autotls.stat.exists == False

- name: THP | Creates tuned profile directory
  when: autotls.stat.exists == False
  file:
    path: /etc/ansibleFlags/autotls
    state: directory
    owner: root
    group: root