- name: Download Cloudera Repo
  get_url:
    url: https://archive.cloudera.com/cm6/6.1.0/redhat7/yum/cloudera-manager.repo
    dest: /etc/yum.repos.d/

- rpm_key:
    state: present
    key: https://archive.cloudera.com/cm6/6.1.0/redhat7/yum/RPM-GPG-KEY-cloudera

- name: Yum | Install Yum packages
  yum:
    name:
      - oracle-j2sdk1.8
      - cloudera-manager-daemons 
      - cloudera-manager-server


# idempotent implementation using folder named "activated" as flag to auto tls
- name: scm_prepare_database | scm_prepare_database?
  stat:
    path: /etc/ansibleFlags/scm_prepare_database
  register: scm_prepare_database

- name: scm_prepare_database | scm_prepare_database init
  command: "echo 'scm' | sudo /opt/cloudera/cm/schema/scm_prepare_database.sh postgresql scm scm"
  when: scm_prepare_database.stat.exists == False

- name: scm_prepare_database | Creates scm_prepare_database
  when: scm_prepare_database.stat.exists == False
  file:
    path: /etc/ansibleFlags/scm_prepare_database
    state: directory
    owner: root
    group: root

- name: Systemd | Enable cloudera-scm-server
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - cloudera-scm-server
